spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/member_db
    username: root
    password: ssggii

  jpa:
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        user_sql_comments: true
        ddl-auto: create

logging:
  level:
    org:
      apache:
        coyote:
          http11: debug

      hiberante:
        SQL: debug

    bobmukjaku:
      bobmukjakuDemo: info
