spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/member_db
    username: root
    password: ssggii

  jpa:
    show-sql: true
    format_sql: true
    hibernate:
      user_sql_comments: true
      ddl-auto: update #create
    open-in-view: false

  profiles:
    include: jwt


logging:
  level:
    org:
      apache:
        coyote:
          http11: debug
