spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mariadb.crzcejb5ip3c.ap-northeast-2.rds.amazonaws.com:3307/bobmukjaku_db
    username: root
    password: ssggii!!

  jpa:
    show-sql: true
    format_sql: true
    hibernate:
      user_sql_comments: true
      ddl-auto: none

  data:
    redis:
      host: 43.202.12.102
      port: 6379
      password: ssggii!!


    open-in-view: false

  profiles:
    include: jwt

  mail:
    host: smtp.gmail.com
    port: 587
    username: bobmukjaku@gmail.com
    password: mkugqklcddnehrrx
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.debug: true

logging:
  level:
    org:
      apache:
        coyote:
          http11: debug

app:
  firebase-bucket: bobmukjaku.appspot.com
